name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: 📦 Install node modules
    - run: npm ci
    - name: 🔨 Build Frontend APP with SSR
    - run: npm run frontend-ssr-build
    - name: 📖 Build Storybook
    - run: npm run storybook
    - name: 💫 Lint code
    - run: npm run lint

